name:                select-random-files
version:             0.1.0.0
github:              "belovachap/select-random-files"
license:             GPLv3
author:              "Chapman Shoop"
maintainer:          "chapman.shoop@gmail.com"
copyright:           "2024 Chapman Shoop"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/select-random-files#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  select-random-files-cli:
    main:                Main.hs
    source-dirs:         app/CLI
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory
    - extra
    - filepath
    - random
    - random-shuffle
    - select-random-files

  select-random-files-gtk:
    main:                Main.hs
    source-dirs:         app/GTK
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cairo
    - gtk
    - select-random-files

tests:
  select-random-files-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - select-random-files
